version: "3"

services:
  nats-server:
    image: nats:2.10.20
    ports:
      - "8222:8222"

  gateway:
    build: ./gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:8000
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=8000
      - NATS_SERVERS=nats://nats-server:4222

  users_microservice:
    build: ./users_microservice
    volumes:
      - ./users_microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=4000
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGODB_URL=${MONGODB_URL_USERS}

  auth_microservice:
    build: ./auth_microservice
    volumes:
      - ./auth_microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=${NATS_SERVERS}

  sessions_microservice:
    build: ./sessions_microservice
    volumes:
      - ./sessions_microservice/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=4002
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGODB_URL=${MONGODB_URL_SESSION}
      - JWT_SECRET=${JWT_SECRET}
