version: "3"

services:
  nats-server:
    image: nats:2.10.20
    ports:
      - "8222:8222"

  gateway:
    build: ./gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:8000
    volumes:
      - ./gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=8000
      - NATS_SERVERS=nats://nats-server:4222

  users:
    build: ./users
    volumes:
      - ./users/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=4000
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGODB_URL=${MONGODB_URL_USERS}

  auth:
    build: ./auth
    volumes:
      - ./auth/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - NATS_SERVERS=${NATS_SERVERS}

  sessions:
    build: ./sessions
    volumes:
      - ./sessions/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=4002
      - NATS_SERVERS=${NATS_SERVERS}
      - MONGODB_URL=${MONGODB_URL_SESSION}
      - JWT_SECRET=${JWT_SECRET}
